---
title: "Cálculo Diferencial"
subtitle: "Verano 2026 - Universidad Continental"
author: "Alexander Josué Meza Medina"
---

::: {.column-screen .text-center style="background-color: #f8f9fa; padding: 2em; margin-bottom: 2em; border-radius: 10px;"}
# Bienvenidos al curso de Cáclculo Diferencial
Aquí encontrarás todo el material actualizado de las sesiones presenciales y remotas.
:::

## 📚 Unidades del Curso

### Unidad 1: Límites de una función
- [Sesión 01: Límite de una función](clase-01-limites.html)
- [Sesión 02: Límites Indeterminados](clase-02-limites-indeterminados.html)
- [Sesión 03: Límites laterales ](clase-03-limites-laterales.html)

### Unidad 2: Derivadas
- [Sesión 04: Derivadas de Funciones Algebraicas](clase-04-derivadas.html)
- [Sesión 05: Fórmulas básicas](clase-05-formulas-basicas.html)
---

## 🛠️ Recursos Adicionales
- [Formulario de Derivadas (PDF)](recursos/formulario.pdf)
- [Software Recomendado: Geogebra](https://www.geogebra.org)

::: {.callout-tip}
## Consejo para el examen
Recuerden revisar los ejercicios resueltos de cada diapositiva, ya que el examen se basará en problemas similares.
:::